blog/urls.py
from django.urls import path
# internals
from . import views
from blog.feed import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post-list'),
    path('drafts', views.drafts, name='drafts'),
    path('new/', views.PostCreateView.as_view(), name='post-create'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post-list-by-tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.post_detail, name='post-detail'),
    path('<int:post_id>/share/', views.post_share, name='post-share'),
    path('feed/', LatestPostsFeed(), name='posts-feed'),
    path('search/', views.post_search, name='post-search'),
]

company/urls.py
from django.urls import path
# internals
from . import views

app_name = 'company'

urlpatterns = [
    path('services/', views.services_list, name='services-list'),
    path('services/<slug:slug>/', views.service_detail, name='service-detail'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [

path('', views.index, name='index')
]

qanda/urls.py
from django.urls import path

from . import views

app_name = 'qanda'

urlpatterns = [

    path('questions/', views.qanda, name='qanda'),
    path('questions/new-question', views.QuestionCreateView.as_view(), name='new-question'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.question_detail, name='question-detail'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
# internals
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),

    path('sitemap.xml', sitemap_view, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

    # path('i18n/', include('django.conf.urls.i18n')),


]
urlpatterns += i18n_patterns(
    path('', include('home.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('qanda/', include('qanda.urls', namespace='qanda')),
    path('users/', include('users.urls', namespace='users')),
    path('company/', include('company.urls', namespace='company')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.conf.urls import url


# internal
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/", views.register_view, name="register"),
    path('profile/', views.profile, name='profile'),
    path('activate/<uidb64>/<token>/',
        views.activate, name='activate'),
]

home/models.py
from django.db import models

# Create your models here.
from core.models import Website
class Masthead(models.Model):
    website = models.OneToOneField(Website, on_delete=models.CASCADE)
    welcome_text = models.CharField(max_length=120)
    masthead_text = models.CharField(max_length=120)
    motto_title = models.CharField(max_length=120)
    motto_description = models.TextField()
    background_image = models.ImageField(upload_to='masthead_background')
    class Meta:
        db_table='t_websitemasthead'

home/views.py
from django.shortcuts import render
from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate, gettext
from django.http.response import HttpResponseRedirect
from django.contrib import messages
from django.db.models import Prefetch
# internals
from company.forms import ContactMessageForm
from core.models import Mail, Phone, Website
from company.models import Address


def queryset_website():
    '''Fetch last active website and pre fetch mails and phones `display` is True '''
    return Website.objects.filter(is_active=True).prefetch_related(
        Prefetch('mails', queryset=Mail.objects.filter(display=True)),
        Prefetch('phones', queryset=Phone.objects.filter(display=True)),
        Prefetch('addresses', queryset=Address.objects.filter(display=True)),
    ).last()


def index(request):
    if request.method == 'POST':
        form = ContactMessageForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, _("Your message has been sent"))
            return HttpResponseRedirect('/')

    else:
        form = ContactMessageForm()
    context = {
        'website': queryset_website(),
        'form': form
    }
    return render(request, 'home/index.html', context)

home/templates/home/about.html
{% load static %}
{% load i18n %}
{% load company_tags %}
<section class="page-section" id="about">
    <div class="container">
        <div class="text-center">
            <a href="{%url 'company:about'%}" class="btn btn-link mb-3">
                <h3 class="section-heading ">
                    {{_('About Us')}}
                </h3>
            </a>
            <h3 class="section-subheading text-muted">{{_('Briefly our story')}}</h3>
        </div>
        <ul class="timeline">
            {% get_milestones as milestones %}
            {% for milestone in milestones %}
            <li class="{%if forloop.counter|divisibleby:2%}{%else%}timeline-inverted{%endif%}">
                <div class="timeline-image"><img class="rounded-circle img-fluid" src="{{milestone.image.url}}"
                        alt="..." /></div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4>{{milestone.date_in.year}}</h4>
                        <h4 class="subheading">{{milestone.title}}</h4>
                    </div>
                    <div class="timeline-body">
                        <p class="text-muted">{{milestone.body}}</p>
                    </div>
                </div>
            </li>
            {%endfor%}
            <li class="timeline-inverted">
                <div class="timeline-image">
                    <h4>
                        {% blocktranslate %}
                        Be Part
                        <br />
                        Of Our
                        <br />
                        Story!
                        {% endblocktranslate %}
                    </h4>
                </div>
            </li>
        </ul>
    </div>
</section>

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title%}{% endblock title%}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{{website.favicon.url}}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body id="page-top">
    {% block home_content %}
    
    {% endblock %}  
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>

home/templates/home/clients.html
{% load static %}
{% load i18n %}
{% load company_tags %}
<div class="py-5">
    <div class="container">
        <h3 class="text-center  text-muted m-3">{{_('Our Clients')}}</h3>
        <div class="row align-items-center">
            {%get_clients as clients %}
            {% with len=clients|length %}
            {%for client in clients %}
            <div class="col-xl-{{len|add:1}} col-md-{{len|add:1}} my-2">
                <a href="{{client.website}}">
                    <img class="img-fluid img-brand d-block mx-auto" src="{{client.image.url}}"
                        alt="{{client.website}}" title="{{client.website}}" />
                </a>
            </div>
            {%endfor%}
            {%endwith%}
        </div>
    </div>
</div>

home/templates/home/contact.html
{% load crispy_forms_tags %}
{% load i18n %}

<section class="page-section" id="contact">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading ">{{_('Contact Us')}}</h2>
            <h3 class="section-subheading text-light">{{_('To contact with us please use the following methods.')}}</h3>
        </div>
        <div class="row align-items-stretch mb-5">
            <div class="col-md-6 text-light">
                <div class="row">
                    <div class="col">
                        <h3>{{_('Email Addresses')}}</h3>
                        <ul>
                            {%for mail in website.mails.all %}
                            <li>{{mail.email}}</li>
                            {%endfor%}
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <h3>{{_('Phone Numbers')}}</h3>
                        <ul>
                            {%for phone in website.phones.all %}
                            <li>{{phone.number}}</li>
                            {%endfor%}
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <h3>{{_('Addresses')}}</h3>
                        <ul>
                            {%for addr in website.addresses.all %}
                            <li>{{addr.full_address}}</li>
                            {%endfor%}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 bg-light p-2 rounded">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-primary text-dark" type="submit">{{_('Submit')}}</button>
                </form>
            </div>
        </div>
    </div>
</section>

home/templates/home/footer.html
{% load i18n %}
<footer class="footer py-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4 text-lg-start">
                {% now "Y" as current_year %}
                {% blocktranslate with website_name=website.name%}
                Copyright &copy; {{website_name}} {{ current_year }}
                {% endblocktranslate %}
            </div>
            <div class="col-lg-4 my-3 my-lg-0">
                {% for sa in website.socialaccounts.all %}
                    <a class="btn btn-dark btn-social mx-2" href="{{sa.url}}"><i class="fab fa-{{sa.slug}}"></i></a>
                {%endfor%}
            </div>
            <div class="col-lg-4 text-lg-end">
                <a class="link-dark text-decoration-none me-3" href="{% url 'company:privacy' %}">{{_('Privacy Policy')}}</a>
                <a class="link-dark text-decoration-none" href="{%url 'company:terms'%}">{{_('Terms of Use')}}</a>
            </div>
        </div>
    </div>
</footer>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block home_content %}

    {% include './navbar.html' %}
    {% include './masthead.html' %}
    {% include './services.html' %}
    {% include './about.html' %}
    {% include './team.html' %}
    {% include './clients.html' %}
    {% include './contact.html' %}
    {% include './footer.html' %}

{% endblock %}

home/templates/home/masthead.html
{% load i18n %}
<header class="masthead" style="background-image: url({{website.masthead.background_image.url}});">
    <div class="container transparent-textarea">
        <div class="masthead-subheading">{{website.masthead.welcome_text}}</div>
        <div class="masthead-heading ">{{website.masthead.masthead_text}}</div>
        <a class="btn btn-primary btn-xl  text-dark" href="#services">{{_('Take a Look Our Services')}}</a>
    </div>
</header>

home/templates/home/navbar.html
{% load static %}
{% load i18n %}

<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top">
            {% if website.logo %}
            <img src="{{website.logo.url}}" alt="..." />
            {% endif %}
            {{website.name}}
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            {{_('Menu')}}
            <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav  ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link" href="#services">{{_('Services')}}</a></li>
                <li class="nav-item"><a class="nav-link" href="#about">{{_('About Us')}}</a></li>
                <li class="nav-item"><a class="nav-link" href="#team">{{_('Our Team')}}</a></li>
                <li class="nav-item"><a class="nav-link" href="#contact">{{_('Contact')}}</a></li>
                <li class="nav-item"><a class="nav-link" href="{%url 'blog:post-list' %}">{{_('Blog')}}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'qanda:qanda' %}">{{_('Q&A')}}</a></li>
                <li class="nav-item dropdown drop-start">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-globe"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}

                        {% for lang in languages %}
                        <li>
                            <a class="dropdown-item{% if lang.code == LANGUAGE_CODE %} active {% endif %}"
                                href='/{{ lang.code }}/{{request.get_full_path|slice:"4:"}}'>
                                {{ lang.code }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{%url 'users:profile' %}" class="nav-link">{{user.username}}</a>
                </li>
                {%endif%}
            </ul>
        </div>
    </div>
</nav>

home/templates/home/services.html
{% load company_tags %}
<section class="page-section" id="services">
    <div class="container">
        <div class="text-center">
            <a href="{% url 'company:services-list'%}">
                <h2 class="section-heading">{{_('Services')}}</h2>
            </a>
            <h3 class="section-subheading text-muted">{{_('Take a look our featured services.')}}</h3>
        </div>
        <div>
        </div>
        {% get_services as services %}
        <div class="row">
            {% for service in services %}
            <div class="col-lg-4 col-md-4 mb-2">
                <div class="card h-100 shadow-sm">
                    <img src="{{service.serviceimage_set.first.image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{service.name}}</h5>
                        <p class="card-text">{{service.description|truncatewords_html:32}}</p>
                        <a href="{% url 'company:service-detail' service.slug %}" class="btn btn-primary">{{_('Browse')}}</a>
                    </div>
                </div>
                <h4 class="my-3"></h4>
                <p class="text-muted"></p>
            </div>
            {% endfor %}
        </div>
        <div class="row text-center">
            <div class="col">
                <a class="btn btn-outline-dark btn-lg shadow" href="{% url 'company:services-list'%}">
                    {{_('All Services')}}
                </a>
            </div>
        </div>
    </div>
</section>

home/templates/home/team.html
{% load static %}
{% load i18n %}
{% load user_tags %}
<section class="page-section bg-light" id="team">
    <div class="container">
        <div class="text-center mb-3">
            <h2 class="section-heading ">{{_('Our Team')}}</h2>
        </div>
        <div class="row">
            {% get_team as team %}
            {% for profile in team %}
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src="{{profile.image.url}}" alt="..." />
                    <h4>{{profile.user.get_full_name}}</h4>
                    <p class="text-muted">{{profile.title}}</p>
                    {% for sa in profile.socialaccounts.all %}
                    <a class="btn btn-dark btn-social mx-2" href="{{sa.url}}"><i class="fab fa-{{sa.slug}}"></i></a>
                    {%endfor%}
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
</section>