blog/urls.py
from django.urls import path
# internals
from . import views
from blog.feed import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post-list'),
    path('drafts', views.drafts, name='drafts'),
    path('new/', views.PostCreateView.as_view(), name='post-create'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post-list-by-tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.post_detail, name='post-detail'),
    path('<int:post_id>/share/', views.post_share, name='post-share'),
    path('feed/', LatestPostsFeed(), name='posts-feed'),
    path('search/', views.post_search, name='post-search'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
# internals
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),

    path('sitemap.xml', sitemap_view, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

    # path('i18n/', include('django.conf.urls.i18n')),


]
urlpatterns += i18n_patterns(
    path('', include('home.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('qanda/', include('qanda.urls', namespace='qanda')),
    path('users/', include('users.urls', namespace='users')),
    path('company/', include('company.urls', namespace='company')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from core.models import Base
# internal
from core.utils import generate_slug
from publish.models import Publish
from .managers import DraftManager, PublishedManager
from ckeditor.fields import RichTextField
from django.utils.translation import ugettext_lazy as _



class Post(Publish):
    STATUS_CHOISES = (
        ('draft', _('Draft')),
        ('published', _('Published')),
    )
    title = models.CharField(max_length=250)
    body = RichTextField()

    slug = models.CharField(max_length=250,
                            unique_for_date='published_date')

    status = models.CharField(max_length=10, choices=STATUS_CHOISES,
                              default='draft')

    published = PublishedManager()
    draft = DraftManager()

    class Meta:
        db_table = 't_blog'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = generate_slug(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post-detail',
                       args=[
                           self.published_date.year,
                           self.published_date.month,
                           self.published_date.day,
                           self.slug
                       ])


class Comment(Base):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    made_by = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 't_comment'
        ordering = ('created_date',)

    def __str__(self):
        return f"Comment by {self.made_by} on {self.post}"

blog/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

# internals
from .models import Comment, Post


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = _('Title')
        self.fields['body'].label = _('Body')
        self.fields['status'].label = _('Status')
        self.fields['tags'].label = _('Tags')

    class Meta:
        model = Post
        fields = ('title', 'body', 'status', 'tags')


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['made_by'].label = _('Made By')
        self.fields['email'].label = _('Email')
        self.fields['body'].label = _('Body')
    class Meta:
        model = Comment
        fields = ('made_by', 'email', 'body')


class SearchForm(forms.Form):
    ALGORITHMS = (
        ("default", "DEFAULT"),
        ("weighting", "WEIGHTING"),
        ("trigram", "TRIGRAM"),
    )
    query = forms.CharField()
    search_algorithm = forms.ChoiceField(choices=ALGORITHMS, required=False)

blog/views.py
import datetime
from django.views import View
from .forms import PostForm
from django.contrib.postgres import search
from django.shortcuts import render, get_object_or_404
from django.core.paginator import (Paginator,
                                   EmptyPage,
                                   PageNotAnInteger)
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.utils.translation import gettext as _
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.auth.models import User
# internals.
from core.utils import elapsed_timer
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from .search import (search_query, search_query_weighting,
                     search_with_trigram_similarity)


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/post/list.html'

# =============================================================================


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post/new.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.get_absolute_url()


@elapsed_timer
def post_search(request):
    form = SearchForm()
    context = {
        'form': form
    }
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_algorithm = form.cleaned_data.get('search_algorithm')
            if search_algorithm == 'trigram':
                results = search_with_trigram_similarity(query)
            elif search_algorithm == 'weighting':
                results = search_query_weighting(query)
            else:
                results = search_query(query)
            context.update({
                'query': query,
                'results': results,
            })
    return TemplateResponse(request, 'blog/post/search.html', context)

# =============================================================================


def post_list(request, tag_slug=None):
    allposts = Post.published.order_by('-comment_count')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        allposts = allposts.filter(tags__in=[tag])
    paginator = Paginator(allposts, per_page=4)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(number=1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(number=paginator.num_pages)

    return render(request, 'blog/post/list.html',
                  {'page': page, 'posts': posts, 'tag': tag})

@login_required
def drafts(request, tag_slug=None):
    allposts = Post.draft.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        allposts = allposts.filter(tags__in=[tag])
    paginator = Paginator(allposts, per_page=2)  # 2 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(number=1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(number=paginator.num_pages)

    return render(request, 'blog/post/drafts.html',
                  {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, slug):
    def queryset():
        qs = Post.objects.prefetch_related('comments').annotate(
            comment_count=Count('comments'))
        return qs

    post = get_object_or_404(queryset(), slug=slug,
                            #  status='published',
                             published_date__date=datetime.date(
                                 year, month, day))
    # list of comments for this post
    comments = post.comments.filter(is_active=True)
    context = {'post': post,
               'comments': comments,
               'similar_posts': get_similar_posts(post)
               }

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            messages.success(request, _("Your comment has been added"))
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()
        context['comment_form'] = comment_form
    return render(request, 'blog/post/detail.html', context)


def get_similar_posts(post: Post):
    # list of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')).order_by('-same_tags', '-published_date')[:4]
    return similar_posts


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(_(subject), _(message), cd['email'], [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html',
                  {'post': post, 'form': form, 'sent': sent})

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}{{ post.title }}{% endblock %}
{% block blog_content %}

<h1 class="text-light">{{ post.title }}</h1>
<div class="d-flex justify-content-between">
    <small class="tags text-light">
        {{_('Tags')}}:
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:post-list-by-tag' tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </small>
</div>
<p class="text-muted">
    {% blocktranslate with pub_date=post.published_date author=post.author %}
    Published {{pub_date}} by {{author}}.
    {% endblocktranslate %}
</p>
<div class="text-light">
    {{ post.body|markdown }}
</div>
<!-- <div class="my-2">
    <a class="btn btn-outline-light" href="{% url 'blog:post-share' post.id %}">
        {{_('Share this post')}}
    </a>
</div> -->
{% with comments.count as total_comments %}
<small class="text-light">
    {{ total_comments }} {{_('comment')}}
</small>
{% endwith %}

<div class="card shadow-sm">
    <div class="list-group">
        {%for comment in comments%}
        <div class="list-group-item comment">
            <p class="info">
                {% blocktranslate with updated_date=comment.updated_date made_by=comment.made_by %}
                    Commented {{updated_date}} by {{made_by}}
                {% endblocktranslate %}
            </p>
            {{comment.body|linebreaks}}
        </div>
        {% empty %}
        <div class="list-group-item list-group-item-warning comment">
            <p class="p-3">{{_('There are no comments yet.')}}</p>
        </div>
        {%endfor%}
    </div>
</div>
<div class="card my-3 p-2 bg-light shadow-sm">
    <h4 class="text-muted">{{_('Add a new comment')}}</h4>
    <form method="post">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <button class="btn btn-primary" type="submit">{{_('Submit')}}</button>
    </form>
</div>
<div class="bg-secondary shadow-sm p-2 mb-4">
    <h5 class="text-white">{{_('Similar posts')}}</h5>
    <div class="list-group list-group-sm">
        {% for post in similar_posts %}
        <a href="{{ post.get_absolute_url }}" class="list-group-item list-group-item-action">
            {{ post.title }}
        </a>
        {% empty %}
        {{_('There are no similar posts yet.')}}
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/post/drafts.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load i18n %}
{% block title %}{{_('Drafts')}}{% endblock %}
{% block blog_content %}
<h2 class="text-muted my-3">{{ _('List of blog posts') }}</h2>
{% if tag %}
<div class="alert alert-info my-2">
    <h5>
        {% blocktranslate with tag_name=tag.name %}
            Posts tagged with "{{ tag_name }}"
        {% endblocktranslate %}
    </h5>
</div>
{% endif %}
<div class="list-group">
    {% for post in posts %}
    <div class="list-group-item">
        <h4>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h4>
        <div class="d-flex justify-content-between">
            <small class="tags">
                {{_('Tags')}}:
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:post-list-by-tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </small>
            <small class="text-muted">
                {% blocktranslate with pub_date=post.published_date author=post.author %}
                    Published {{pub_date}} by {{author}}.
                {% endblocktranslate %}
            </small>
        </div>
        <p>
            {{ post.body|markdown|truncatewords_html:40 }}
        </p>
    </div>
{% endfor %}
</div>
<!-- Since the Page object you are passing to the template is called posts , you include
the pagination template in the post list template, passing the parameters to render
it correctly. -->
{% include "pagination.html" with page=posts %}
<!-- Django's ListView generic view passes the selected page
in a variable called page_obj , so you have to edit your post/list.html template
accordingly to include the paginator using the right variable, as follows -->
<!-- {% include "pagination.html" with page=page_obj %} -->
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load i18n %}
{% block title %}{{_('Blog')}}{% endblock %}
{% block blog_content %}
<h2 class="text-muted my-3">{{ _('List of blog posts') }}</h2>
{% if tag %}
<div class="alert alert-info my-2">
    <h5>
        {% blocktranslate with tag_name=tag.name %}
            Posts tagged with "{{ tag_name }}"
        {% endblocktranslate %}
    </h5>
</div>
{% endif %}
<div class="list-group">
    {% for post in posts %}
    <div class="list-group-item bg-light my-2 shadow-sm">
        <h4>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h4>
        <div class="d-flex justify-content-between">
            <small class="tags">
                {{_('Tags')}}:
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:post-list-by-tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </small>
            <small class="text-muted">
                {% blocktranslate with pub_date=post.published_date author=post.author %}
                    Published {{pub_date}} by {{author}}.
                {% endblocktranslate %}
            </small>
        </div>
        <p>
            {{ post.body|markdown|truncatewords_html:40 }}
        </p>
    </div>
{% endfor %}
</div>
<!-- Since the Page object you are passing to the template is called posts , you include
the pagination template in the post list template, passing the parameters to render
it correctly. -->
{% include "pagination.html" with page=posts %}
<!-- Django's ListView generic view passes the selected page
in a variable called page_obj , so you have to edit your post/list.html template
accordingly to include the paginator using the right variable, as follows -->
<!-- {% include "pagination.html" with page=page_obj %} -->
{% endblock %}

blog/templates/blog/post/new.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}{{_('New Blog Post')}}{% endblock %}
{% block blog_content %}
    <div class="content-section bg-light p-2 rounded p-2 mb-4" style="background-color: #eee;">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                <!-- {{ form|crispy }} -->
                {% for field in form %}
                <p>
                    {% if field.label %}{{field.label_tag}}<br/>{% endif %}
                    {{ field }}
                </p>
                    {% if field.errors %}{{ field.errors }}{% endif %}
                {% endfor%}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-lg btn-primary" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock blog_content %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load i18n %}

{% block title %}{{_('Search Page')}}{% endblock %}

{% block blog_content %}
<div class="card">
    <h5 class="card-title alert alert-info p-3">{{_('Search for posts')}}</h5>
    <div class="card-body">
        <form class="d-flex justify-content-around row" method="GET" action="{% url 'blog:post-search' %}">
            <div class="col-lg-6">
                <input class="form-control me-2" value="{%if query%}{{query}}{%endif%}" type="search" name="query"
                    placeholder="{{_('Search')}}" aria-label="Search" />

            </div>
            <div class="col-lg-4 my-1">
                <select name="search_algorithm" class="form-select form-select-sm"
                    aria-label=".form-select-sm searching">
                    <option value="default" selected>{{_('Select algorithm')}}</option>
                    <option value="default">{{_('Default')}}</option>
                    <option value="weighting">{{_('Weighting')}}</option>
                    <option value="trigram">{{_('Trigram')}}</option>
                </select>
            </div>
            <div class="col-lg-1">
                <button class="btn btn-sm btn-outline-dark btn-sm my-1" type="submit">{{_('Search')}}</button>
            </div>
        </form>
    </div>
</div>
<div class="d-flex justify-content-between my-3 bg-secondary text-light rounded p-2">
    <h5>
        {% blocktranslate with _query=query %}
        Posts containing "{{ _query }}"
        {% endblocktranslate %}
    </h5>
    <h6>
        {% blocktranslate count results.count as _total %}
        Found {{_total}} result.
        {% plural %}
        Found {{_total}} results.
        {% endblocktranslate %}
    </h6>
</div>
<div class="my-1">
    <small>{{ elapsed_time }} {{ _('seconds')}}</small>
</div>
<div class="list-group">
    {% for post in results %}
    <div class="list-group-item">
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        <p>
            {{ post.body|markdown|truncatewords_html:5 }}
        </p>
    </div>
    {% empty %}
    <p>{{_('There are no results for your query.')}}</p>
    {% endfor %}
</div>




{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{{_('Share a post')}}{% endblock %}
{% block blog_content %}
<div class="bg-light m-2 p-2 rounded">
    {% if sent %}
        <h3>{{_('E-mail successfully sent')}}</h3>
        <p>
            {% blocktranslate with post_title=post.title receiver=form.cleaned_data.to%}
            "{{ post_title }}" was successfully sent to {{ receiver }}.
            {% endblocktranslate%}
        </p>
        {% else %}
        <h3 class="">
            {% blocktranslate with post_title=post.title%}
            Share "{{ post_title }}" by e-mail
            {% endblocktranslate%}
        </h3>
        <form method="post">
            {% csrf_token %}
            {{form | crispy}}
            <button class="btn btn-primary" type="submit">{{_('Send Email')}}</button>
        </form>
    {% endif %}
</div>
{% endblock %}