src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
# internals
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),

    path('sitemap.xml', sitemap_view, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

    # path('i18n/', include('django.conf.urls.i18n')),


]
urlpatterns += i18n_patterns(
    path('', include('home.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('qanda/', include('qanda.urls', namespace='qanda')),
    path('users/', include('users.urls', namespace='users')),
    path('company/', include('company.urls', namespace='company')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.conf.urls import url


# internal
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/", views.register_view, name="register"),
    path('profile/', views.profile, name='profile'),
    path('activate/<uidb64>/<token>/',
        views.activate, name='activate'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    phone_number = models.CharField(max_length=24)
    title = models.CharField(max_length=60, null=True)
    has_team = models.BooleanField(default=False)

    class Meta:
        db_table = 't_profile'

    def __str__(self) -> str:
        return f"Profile {self.user.username}"

users/forms.py
from django import forms
from django.db.models import Q
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from django.contrib.auth.forms import (UserCreationForm, AuthenticationForm)

from users.models import Profile


class CustomUserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = _("Email")
        self.fields['email'].help_text = _('Enter your email.')

    class Meta:
        model = User
        fields = ('username', 'email')


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = _("Email")
        # self.fields['email'].help_text = _('Enter your email.')

    class Meta:
        model = User
        fields = ('username', 'email')


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

users/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.utils.translation import gettext as _
from django.views.generic.edit import View
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage
from django.urls import reverse_lazy

# internals
from .forms import CustomUserLoginForm, CustomUserCreationForm
from core.models import Website
from .forms import (UserUpdateForm, ProfileUpdateForm)
from .tokens import get_account_activation_token


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and get_account_activation_token().check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, 'users/email_confirmation_done.html')
    else:
        return HttpResponse('Activation link is invalid!')


def register_view(request):
    form = CustomUserCreationForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            _template = 'users/activate_user.html'
            url = reverse_lazy('users:activate',
                               kwargs={
                                   'uidb64': urlsafe_base64_encode(force_bytes(user.pk)),
                                   'token': get_account_activation_token().make_token(user),
                               })
            activate_url = '{}{}'.format(current_site.domain, url)
            _context = {
                'user': user,
                'activate_url': activate_url,
            }
            mail_subject = _('Activate your account.')
            message = render_to_string(_template, _context)
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.content_subtype = "html"
            email.send()
            return render(request, 'users/email_confirmation.html')
    context = {
        'form': form,
        'website': Website.objects.first()
    }
    return render(request, 'users/register.html', context)


def login_view(request):
    if request.user.is_authenticated:
        return redirect("/")
    form = CustomUserLoginForm(data=request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        raw_pass = form.cleaned_data.get("password")
        user = user = authenticate(
            request, username=username, password=raw_pass)
        login(request, user)
        return redirect("/")
    context = {
        'form': form,
        'website': Website.objects.first()
    }
    return render(request, "users/login.html", context)


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST,
                                         request.FILES,
                                         instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Your account has been updated!'))
            return redirect('users:profile')

    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    return render(request, 'users/profile.html', context)

users/templates/users/activate_user.html
{% autoescape off %}
{{_('Hi')}} {{ user.username }},
{{_('Please click on the link to confirm your registration,')}}
<a href="{{ activate_url }}">{{ activate_url }}</a>
{% endautoescape %}

users/templates/users/email_confirmation.html
{% extends 'base.html'%}
{% load static %}
{% load i18n %}
{% block root_content %}
<div class="alert alert-primary">
    <h4>
        {{_('Please confirm your email address to complete the registration')}}
    </h4>
</div>
{%endblock%}

users/templates/users/email_confirmation_done.html
{% extends 'base.html'%}
{% load static %}
{% load i18n %}
{% block root_content %}
<div class="alert alert-success">
    <h4>
        {{_('Thank you for your email confirmation. Now you can login your account.')}}
        <a style="margin: 10px;" href="{% url 'users:login' %}">{{_('Login')}}</a>
    </h4>
</div>
{% endblock root_content %}

users/templates/users/login.html
{% extends 'base.html'%}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block root_content %}
<section class="h-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-10">
                <div class="card rounded-3 text-black">
                    <div class="row g-0">
                        <div class="col-lg-6 d-flex align-items-center bg-secondary">
                            <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                {% if website %}
                                <h4 class="mb-4">{{ website.masthead.motto_title }}</h4>
                                <p class="small mb-0">
                                    {{ website.masthead.motto_description }}
                                </p>
                                {% else %}
                                <h4 class="mb-4">{{_('Welcome to the site!')}}</h4>
                                <p class="small mb-0">
                                    {{_('We wish you to have a nice moments in our site.')}}
                                </p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="card-body p-md-5 mx-md-4">
                                <div class="text-center">
                                    {% if website %}
                                    <img src="{{website.logo.url}}" style="width: 185px;" alt="logo">
                                    <h4 class="mt-1 mb-5 pb-1">{{ website.name }}</h4>
                                    {% endif %}
                                </div>
                                <form method="POST">
                                    {% csrf_token %}
                                    <fieldset class="form-group">
                                        <legend class="border-bottom mb-4">{{ _('Login') }}</legend>
                                        {{ form|crispy }}
                                    </fieldset>
                                    <div class="form-group my-2 d-flex justify-content-between">
                                        <button class="btn btn-outline-primary" type="submit">{{_('Submit')}}</button>
                                        <!-- <small class="text-muted">
                                            <a class="ml-2 disabled"
                                                href="{% url 'users:register' %}">{{_('Register')}}</a>
                                        </small> -->
                                    </div>
                                </form>
                                <div class="border-top mt-3">
                                    <small class="text-muted">
                                        {{_('Forgot password ?')}} <a class="ml-2 disabled"
                                            href="{% url 'password_reset' %}">{{_('New Password')}}</a>
                                    </small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

users/templates/users/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block root_content %}
<div class="content-section bg-light p-2 rounded">
    <div class="row">
        <div class="col-lg-6">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">{{_('Reset Password')}}</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group my-2">
                    <button class="btn btn-primary" type="submit">{{_('Request Password Reset')}}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}
{% block root_content %}
    <div class="alert alert-info">
        {{_('Your password has been set.')}}
    </div>
    <a class="btn btn-primary" href="{% url 'users:login' %}">{{_('Login')}}</a>
{% endblock%}

users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block root_content %}
    <div class="content-section bg-light p-2 rounded">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{_('Reset Password')}}</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group my-2">
                <button class="btn btn-primary" type="submit">{{_('Submit')}}</button>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}
{% block root_content %}
    <div class="alert alert-info">
       {{_('An email has been sent with instructions to reset your password')}}
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block root_content %}
    <div class="content-section bg-light p-2 rounded bg-light p-2">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">{{_('Profile Info')}}</legend>
              {{ user_form|crispy }}
              {{ profile_form|crispy }}
          </fieldset>
          <div class="form-group my-2">
              <button class="btn btn-primary" type="submit">{{_('Update')}}</button>
          </div>
      </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html'%}
{% load static %}
{% load crispy_forms_tags %}

{% block root_content %}
<section class="h-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-10">
                <div class="card rounded text-black">
                    <div class="row g-0">
                        <div class="col-lg-6">
                            <div class="card-body p-md-5 mx-md-4">
                                <div class="text-center">
                                    {% if website %}
                                    <img src="{{website.logo.url}}" style="width: 185px;" alt="logo">
                                    <h4 class="mt-1 mb-5 pb-1">{{ website.name }}</h4>
                                    {% endif %}
                                </div>
                                <form method="POST">
                                    {% csrf_token %}
                                    <fieldset class="form-group">
                                        <legend class="border-bottom mb-4">{{_('Register')}}</legend>
                                        {{ form|crispy }}
                                    </fieldset>
                                    <div class="form-group my-2">
                                        <button class="btn btn-outline-primary" type="submit">{{_('Submit')}}</button>
                                        <small class="text-muted">
                                            {{_('Have account ?')}} <a class="ml-2 disabled"
                                                href="{% url 'users:login' %}">{{_('Login')}}</a>
                                        </small>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="col-lg-6 d-flex align-items-center bg-dark">
                            <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                {% if website %}
                                <h4 class="mb-4">{{ website.attributes.motto.title }}</h4>
                                <p class="small mb-0">
                                    {{ website.attributes.motto.description }}
                                </p>
                                {% else %}
                                <h4 class="mb-4">{{_('Welcome to the site!')}}</h4>
                                <p class="small mb-0">
                                    {{_('We wish you to have a nice moments in our site.')}}
                                </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}