blog/urls.py
from django.urls import path
# internals
from . import views
from blog.feed import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post-list'),
    path('drafts', views.drafts, name='drafts'),
    path('new/', views.PostCreateView.as_view(), name='post-create'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post-list-by-tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.post_detail, name='post-detail'),
    path('<int:post_id>/share/', views.post_share, name='post-share'),
    path('feed/', LatestPostsFeed(), name='posts-feed'),
    path('search/', views.post_search, name='post-search'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [

path('', views.index, name='index')
]

qanda/urls.py
from django.urls import path

from . import views

app_name = 'qanda'

urlpatterns = [

    path('questions/', views.qanda, name='qanda'),
    path('questions/new-question', views.QuestionCreateView.as_view(), name='new-question'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.question_detail, name='question-detail'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
# internals
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),

    path('sitemap.xml', sitemap_view, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

    # path('i18n/', include('django.conf.urls.i18n')),


]
urlpatterns += i18n_patterns(
    path('', include('home.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('qanda/', include('qanda.urls', namespace='qanda')),
    path('users/', include('users.urls', namespace='users')),
    path('company/', include('company.urls', namespace='company')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.conf.urls import url


# internal
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/", views.register_view, name="register"),
    path('profile/', views.profile, name='profile'),
    path('activate/<uidb64>/<token>/',
        views.activate, name='activate'),
]

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        crossorigin="anonymous">
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="bg-dark">
    <main class="container-xl">
        {% include 'navbar.html' %}
        <div class="container-fluid mt-4">
            {% if messages %}
            {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}"
                role="alert">{{ message }}</div>
            {% endfor %}
            {% endif %}
            {% block root_content %}
            {% endblock %}
        </div>
    </main>
    <!-- javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
    <!-- CK-Editor -->
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static  'ckeditor/ckeditor/ckeditor.js' %}"></script>
</body>

</html>

templates/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">{{_('Site')}}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">{{_('Home')}}</a>
                </li> -->
                <li class="nav-item dropdown">
                    <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">{{_('Blog')}}</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item active" href="{% url 'blog:post-list' %}">{{_('Posts')}}</a></li>
                        {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'blog:drafts' %}">{{_('Drafts')}}</a></li>
                        <li><a class="dropdown-item" href="{% url 'blog:post-create' %}">{{_('New Blog Post')}}</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'qanda:qanda' %}">{{_('Q&A')}}</a>
                </li>
                <li class="nav-item dropdown drop-start">
                    <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-globe"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}

                        {% for lang in languages %}
                        <li>
                            <a class="dropdown-item{% if lang.code == LANGUAGE_CODE %} active {% endif %}"
                                href='/{{ lang.code }}/{{request.get_full_path|slice:"4:"}}'>
                                {{ lang.code }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>

            <form class="d-flex align-items-center text-center w-100 me-3 mt-2" method="GET"
                action="{% url 'blog:post-search' %}">
                <input class="form-control form-control-sm me-2" type="search" name="query"
                    placeholder="{{_('Search on blog')}}" aria-label="Search">
                <button class="btn btn-outline-light btn-sm mb-2 " type="submit">{{_('Search')}}</button>
            </form>
            {% if user.is_authenticated %}
            <div class="dropdown">
                <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{{ user.profile.image.url }}" alt="{{user.username}}" width="32" height="32"
                        class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item" href="{% url 'users:profile' %}">{{_('Profile')}}</a></li>
                    {% if user.is_superuser %}
                    <li><a class="dropdown-item" href="/admin/">Admin</a></li>
                    {% endif %}
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'users:logout' %}">{{_('Log Out')}}</a></li>
                </ul>
            </div>
            {% else %}
            <a class="btn btn-sm btn-light" href="{% url 'users:login' %}">
                <small>{{_('Login')}}</small>
            </a>
            {% endif %}
        </div>
    </div>
</nav>